name: Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Test Next.js
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      # Install dependencies
      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install

      # Setup .env
      - name: Copy .env.example files
        shell: bash
        run: find . -type f -name ".env.example" -exec sh -c 'cp "$1" "${1%.example}"' _ {} \;

      # Typechecker
      - name: Typecheck
        run: pnpm typecheck

      # Linter
      - name: Lin
        run: pnpm lint

      # Run tests
      - name: Run Tests
        run: npm run test

      # Build the application
      - name: Build Next.js App
        run: npm run build

#   deploy:
#     name: Deploy to Vercel
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#       # Checkout the repository
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       # Install Node.js
#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'
#           cache: 'npm'

#       # Deploy to Vercel
#       - name: Deploy to Vercel
#         env:
#           VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
#         run: npx vercel --prod